apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: above-the-clouds-web-server-stg-ip
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.allow-http: "false"
  labels:
    app: frontend
spec:
  backend:
    serviceName: frontend
    servicePort: 80
